"""Ajout de la colonne livreFavoris à User

Revision ID: f00c623d04b7
Revises: adbd6ab8e4ce
Create Date: 2024-06-29 20:57:28.132344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00c623d04b7'
down_revision = 'adbd6ab8e4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('livreFavoris', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('livreFavoris')

    # ### end Alembic commands ###
