#script de migration
"""Ajouter la colonne prix à la table book sans contrainte NOT NULL

Revision ID: f7a871912e06
Revises: f00c623d04b7
Create Date: 2024-06-30 21:31:10.446248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a871912e06'
down_revision = 'f00c623d04b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prix', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('prix')

    # ### end Alembic commands ###
